language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: LVcxCcUvp8pmkmQOiy/5kRdDEMxsD1PKgRzfjZOpdIwQkLgoxmaoIRZg8U5ryUt+h9PTO4s2TqCjZjotjWBLexCW2OvUwBEWXuEcUCKY/wWyrkFAEue5QIeNUDlLoQhie4EGOnPNjwatlUdYn/vpNZo4p2QeIYyD+1NdjiW+SafCpOel3pdznQmVq/EDJv7nnKcDzHDep2T0aVSqwgbX2yJrEoMq9pGMgd+U8bWsYONbbGSnD0BePI4xc5lPfgOdwZMP1dNxa3IdLZ+Bdtk/oWmRGRT01CnJhcMGLLC1A69KllWfFtxB5uTe6by3L71Ci/ydLdlyaCFuW9IzphAxvvEPCSt5rT5XCvaNVhXH4HcxIgot3mP50nwz4X74dwH/JyiVg8p7Hf3dhK1x4f/2zNlSdjk7biFa7gdYJuzuDBOXI8Y2CCG7Ayyor24Ni13O51iCkBj3xZckFsQKhpnTHyZ8p7xBsgL3f5aXIvzsu6kE8rLMVj4Maw3psSFF0+1UxbfodhLCfIY+fuXcodcJEo8iuSLKyEo2iBtQ6ZZ9p9vLS2MleKMEPIgPVrdS9p2PW4fgRJHLX5ESCGON+n+DCNTNl1NApb8JyKQYiAEIYb2ji0qkSxzph83UUNYzrYMYAq97LUgx6sFfs5prHSH4lj1OYhvB1hM8jQffgP01tg4=
  - secure: Av5HXaHxBCiRclVZTxstecWW+kKF4yHiyH6qjqARTlYhJYaPnWIHkYfUHzPjnSGKbtxffT5SwPILA7lY8wakvip5678yy+dQNYlcndO/amcUKLdqOOh0oX2YIoYBbCnkYykWgJmGeoxVrbiEi1qma3Mk2CNCAE7lpXc6Mzn+0M2h74YlWv2Lp/bVSURkG9aYLzEZtdfE7x+3gGKBYPVT6hGYpFaBhePa4HFtAdmMbUocj+nsTE41xmH1A3zkEYnye5IfdhlTu0WOqLUmmZnLYbjtt9Y0CjXIKBqepiHO5EU9MoehEcuBKeQyfDEbgRPOtO3AQNs119p3wv/nioAF/W6C7cHUtVT7hgq9QW2PA5SZuDeLg8dC5RfBNP5EaFF2UJcvwxNSB3yRFPehAhnmqMyLrMBeVDG7cOBmseavYZF19jFtraUmD+diBI0pbuQTI8GA8tQxNxBVtW1Mas7uKRUQWk0qwCxMaybVNyPrEiANKsy4GP25kwOXqx2KysC1PMZP0WXQpdmAQqoSbgIRFYFWMWS095CgcPv1Zgm0SU/aO/H4iYxV7lSEROdyrwUthyQVC5mEn/7akPBSUvJXGgA3UYlB8kJ3eBq5owAfQGR4g8r5oSIJlyD/GByWijPVf4xzGBUI3BhQSVKf9NtMRn4jOpyUSHZI4l9SnxMo+9M=
