language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: cKUUd5RKYTT2TDKIXewsP7XPboPg50r5LyuBdU2pQ8D1wUEd1pZ0hjRgIy26t4kif8tQt9jR4J56mRuMll5sgrycc0su4l09qIij2qr/WOoqEph3404/fLvb3+HaLf4minYA2P1tzp70rCXZL8/13ZCgF31S5N/oUvXC/I06Xh/1Mj87LUzImvmsCTlHEtuBkI4q8tEViUlwb8Xr7Tvop/MrWsmhGCITk01/WdU4HvePewUScwHRv+zTKdO+6FP+bzLOIs3TZVp4rMGqVYIt6HtONFwZvYmn+7lqxjsbvgrNzl1s4T1MAgGtTQTM/1ti5UfNPwyWPizkkUtR/4coqGahJ9umCnZVCsWHruzCKt8W+uZ65KFDcZ8YOyApts2CgLwk9WzL9wHsbEi0kFUMAF3BfwfwK2BcGpipruxoEe9tRpgZkanG3mJBXlchjx0UVDKM3/y/p5ZrI8XR0fvpwVBrkkqLaSrwUcAohDZ5YdBeLH2N4qDbk11FJscoukftWzQndhI+v4/KXCP8oP+YkD0QW1xFUaA0wukidQdXtpCRXZzdd2x/ICCAO9jR4xVbJdOcHtmLYfwySWyQ6igP4SVF0VI8GXCJ0tqCkpKpgcGxbxBiPs/iIXES6yJiwL6x5revZoL2nINXfl20J4QNmXKPQGXUZxB1bGjBc1cAULA=
  - secure: dvBt8O9udqu5N69AUMKQVDALdWfuoJGKDF62Ng/pxh/5RInciWbhYYzEDP1+hu7SdpLzIVSd43b+V4e1BpPC3B2jYrtK2ApxQotx/HetJ9qF0SSD0du5Fsk1w9aumcj2hBbsDjxHUmVaLN+Mhn9/yVKmUS2v2XQow5oWozvNq3ZF7HbCnuJl+YW9yeQWkkWbn3pKabdAwL3W4ax6TecfFNwbc2rwsOW9RRybOECXicOckFt2J/gbQNQ5EMUfRRb6zDR5hCdgvde9XIRmsRlLBSK4RPpVS9i6QEg9Kj2Rgj4PjCKxn47/C+Z/5LpWlTSR1fleehEJzCd7qxQnvzhuCNM8bB0RPswpHbbEPoqZQJ4qMfIi74Dp7GCGhJQQjZ0m/iMqnboz5C/ggBlzGAdJ4LS++Z5Q+IZn4ew5E+HeaQqcQSimDcz9wRkbREmLlDlsH21/IPnQIwg8n1xykUGVUyZKYASVajUw3Y40qv6QS+1aMG3McxdSr+MiKdfCcsOZnVfy9u6DGU4rWNhU+3JQ0Rrhe++6QEEzIDV6CZEAGwJOm7MPe9Rsfzt/cxdYo+QpozcUMJAECrajT8AnhCCw3SKc6ZUY81C337KEZfJBEGlkxE6mWI1MtXf56yzbWsbnEBVcMUINRaIiaW15gsS/O7R6O93uTeZtTRJF2azuxuQ=
