title = "12542 SW 107 Ct Miami, FL 33176"
baseURL = "https://www.featuredlistingforsale.com"
tags = ["miami", "real estate", "listing"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = ""
    author = "Toma Nistor"
    description = "Pine Shore! 4/2 Empire model, family home, newer roof 2013, wood & porcelain tile, sitting on a 15,000 SQ. FT."
    logoBig = ""
    logoSmall = ""
    favicon = "favicon.ico"
    opengraphImage = ""
    twitter = "yourhomemiami"
    linkedin = "dianaiordonez"
    github = ""
    facebook = "dianaiordonezsanchez"
    email = "futuresarcade@gmail.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

# [[menu.main]]
  #  name = "About"
  #  url  = "/#about"
  #  weight = 1
# [[menu.main]]
  #  name = "Work"
  #  url  = "/#work"
  #  weight = 2
# [[menu.main]]
  #  name = "Blog"
  #  url  = "/#blog"
  #  weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
